apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-watchlist-config
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: movie-watchlist-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://movieuser:moviepass@postgres:5432/movies"
